name: TUL-SMP
version: '${project.version}'
main: me.pycrs.tulsmp.TulSmp
api-version: 1.15
authors: [ Pycrs ]
commands:
  playtime:
    description: Playtime command
    usage: /<command>
  whois:
    description: Who's osobni cislo is this?
    usage: /<command> <osCislo>
